### ISSUE TITLE
Add new parameter "spaces" for extraction of numbers

### ISSUE THREAD

**Issue by rcepka** [rorynolan/strex#10]
Hello,

first of all, thank you for this package. I started to use it just recently and I found it very useful.

I just came across the issue of extracting numbers from strings, if the "big mark" separation character is space. For example, number  in format "2 500" is extracted as 2; instead of 2500.
I am aware of parameter "commas", which solves this problem when big mark separator is comma; but what about space? May I suggest to implement this number separator too? 
Many thanks in advance.

**Comment by rorynolan** [comment]
Hello @rcepka 
Always delighted to hear from a package fan!
Thank you for your suggestion. It is great and I have edited the package accordingly with the replacement of `commas` with `big_mark`. You should now be able to use `big_mark = " "` to achieve what you want.
It will take me a while to get this onto CRAN but for now are you able to install from GitHub and let me know what you think?
Thanks,
Rory

**Comment by rcepka** [comment]
Hello @rorynolan ,

wau, that was lighting fast reaction, thank you 👍 

I did some light testing and it works like a charm, I did not encounter any issue. I tested it with the "str_nth_number_after_mth()" family of functions, which I find particularly useful and results are OK, no issues. The number gets parsed correctly according to settings.  
I also like your solution, way of implementation; it is flexible for all types of locales. 

Thank you very much once again; for the package and also for you fast and awesome reaction.

**Comment by rorynolan** [comment]
Hi @rcepka
Thanks for testing it so fast and glad it's working and you like it ♥
I will close this thread when I manage to get it onto CRAN. Will probably be in next few weeks.

**Comment by rorynolan** [comment]
Made it to CRAN!
Thanks again @rcepka for the great suggestion.

**Comment by rcepka** [comment]
Hello @rorynolan , 
perfect, thank you; also for your superb support and, once again, for this great package.
