### ISSUE TITLE
_strex_intmat_list_bind_nth_rows

### ISSUE THREAD

**Issue by kuraisle** [rorynolan/strex#2]
Hello!

I'm afraid I can't attach a reprex because it's not my issue. I'm helping a colleague to use your packages nandb and ijtiff. I had no issues using it, but when she came to run the exact same code, running read_tif gave the error that "intmat_list_bind_nth_rows" could not be found. I had a little delve through what read_tif calls, and eventually my fix was to email her my copy of strex. It works for us both now. I see you updated strex over the weekend. I have version 0.1.3 and my colleague would have had version 1 I guess.

I know this isn't really the vehicle for this, but the nandb package is going to be very handy, so thanks!

**Comment by rorynolan** [comment]
Hi @kuraisle,
This is my fault. I updated `strex` recently, which broke `filesstrings`. Then `ijtiff` and `nandb` which rely on `filesstrings` were broken by association. I need to fix `filesstrings` and then update `ijtiff` and `nandb` to rely on the up-to-date `filesstrings`. This will take a couple of weeks. I'll let you know when I've done that. I'm sorry your colleague got caught by this, poor planning on my part.
A little tip, to install an old version of a package, you can use `remotes::install_version("strex", "0.1.3")`.
Delighted to hear you're using and liking `nandb`. I hear so seldom from users that it's a relief to know that I have some!

**Comment by kuraisle** [comment]
I'll just make sure not to update my packages until then! No need to
apologise, no harm done! Not only do you have some users, you're likely to
have more coming, especially if I finish the GUI I've been making for it in
shiny!

**Comment by rorynolan** [comment]
Oh wow this is very exciting! I'll make sure to notify you personally about any changes to `nandb`!

**Comment by rorynolan** [comment]
Hi @kuraisle 
The newest version of `nandb` is now on CRAN and it will have no such `strex`-related issues! People now just need to make sure they're using `nandb` v2.0.2 or higher (can be checked with `packageVersion("nandb")`). Good luck with the shiny app and let me know how its going and if you need any help.
Thanks,
Rory

**Comment by kuraisle** [comment]
Hi Rory,

Thanks for letting me know!

Cheers,
James
