### ISSUE TITLE
Parameter names confused in str_trim_anything()

### ISSUE THREAD

**Issue by salim-b** [rorynolan/strex#4]
https://github.com/rorynolan/strex/blob/2124d20eb284cd2d4fd728bcd158f398c27b3035/R/trim.R#L9-L11

It looks like in an earlier version of this function, the "ancestor" of parameter `pattern` was named `char` and only supported a single character.

BTW: IMHO it's rather confusing to name a parameter `pattern` while its value isn't interpreted as a regular expression – especially since this package is designed as a supplemention to stringr which interprets all its `pattern` params as regexes! Plus: The function `str_trim_anything()` would actually be more useful if `pattern` could be a regex.

**Comment by rorynolan** [comment]
Hello @salim-b 
I agree with you and I've now changed it so that `pattern` can be a regex and `str_trim_anything()` behaves like a `stringr` function.
I'll submit to CRAN in a few days. Feel free to take a look and suggest more stuff.
Thanks.

**Comment by salim-b** [comment]
Hi @rorynolan 

Thanks, sounds good! I'll have a look when it's ready :)

**Comment by rorynolan** [comment]
It's ready now on GitHub and will be on CRAN soon. I'm gonna close this issue now but feel free to reopen if you spot something.
Thanks again.
